import jsPDF from "jspdf";
import type { TripPlan } from "@shared/schema";

export function generateTripPDF(tripPlan: TripPlan): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = 20;

  // Title
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("Your Dream Vacation Itinerary", pageWidth / 2, y, { align: "center" });
  y += 15;

  // Destination
  doc.setFontSize(16);
  doc.setTextColor(0, 102, 204);
  doc.text(`${tripPlan.destination.name}, ${tripPlan.destination.country}`, margin, y);
  y += 10;

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Match Score: ${tripPlan.destination.matchScore}/100`, margin, y);
  y += 6;
  
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  const descriptionLines = doc.splitTextToSize(tripPlan.destination.description, pageWidth - 2 * margin);
  doc.text(descriptionLines, margin, y);
  y += descriptionLines.length * 5 + 10;

  // Budget Summary
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("Budget Summary", margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Flights: $${tripPlan.budget.breakdown.flights.toLocaleString()}`, margin + 5, y);
  y += 6;
  doc.text(`Accommodation: $${tripPlan.budget.breakdown.accommodation.toLocaleString()}`, margin + 5, y);
  y += 6;
  doc.text(`Activities: $${tripPlan.budget.breakdown.activities.toLocaleString()}`, margin + 5, y);
  y += 6;
  doc.setFont("helvetica", "bold");
  doc.text(`Total: $${tripPlan.budget.breakdown.total.toLocaleString()}`, margin + 5, y);
  y += 12;

  // Selected Flight
  if (tripPlan.selectedFlight) {
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Flight Details", margin, y);
    y += 8;

    const flight = tripPlan.selectedFlight;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`${flight.airline} - ${flight.class.toUpperCase()}`, margin + 5, y);
    y += 6;
    doc.text(`${flight.departureCity} → ${flight.arrivalCity}`, margin + 5, y);
    y += 6;
    doc.text(`Departure: ${flight.departureTime} | Arrival: ${flight.arrivalTime}`, margin + 5, y);
    y += 6;
    doc.text(`Duration: ${flight.duration} | Stops: ${flight.stops}`, margin + 5, y);
    y += 12;
  }

  // Selected Hotel
  if (tripPlan.selectedHotel) {
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Accommodation", margin, y);
    y += 8;

    const hotel = tripPlan.selectedHotel;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`${hotel.name} (${"⭐".repeat(hotel.stars)})`, margin + 5, y);
    y += 6;
    doc.text(`$${hotel.pricePerNight}/night × 7 nights = $${hotel.totalPrice}`, margin + 5, y);
    y += 6;
    doc.text(`Rating: ${hotel.rating}/5 (${hotel.reviewCount} reviews)`, margin + 5, y);
    y += 6;
    const reasoningLines = doc.splitTextToSize(hotel.aiReasoning, pageWidth - 2 * margin - 10);
    doc.text(reasoningLines, margin + 5, y);
    y += reasoningLines.length * 5 + 10;
  }

  // New page for itinerary
  doc.addPage();
  y = 20;

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Day-by-Day Itinerary", margin, y);
  y += 12;

  // Iterate through days
  tripPlan.itinerary.days.forEach((day, index) => {
    // Check if we need a new page
    if (y > 250) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 102, 204);
    doc.text(`Day ${day.day} - ${day.date}`, margin, y);
    y += 8;

    day.activities.forEach((activity) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }

      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(0, 0, 0);
      doc.text(`${activity.time} - ${activity.name}`, margin + 5, y);
      y += 5;

      doc.setFont("helvetica", "normal");
      doc.setTextColor(60, 60, 60);
      const activityLines = doc.splitTextToSize(activity.description, pageWidth - 2 * margin - 10);
      doc.text(activityLines, margin + 5, y);
      y += activityLines.length * 4;

      if (activity.cost > 0) {
        doc.setTextColor(100, 100, 100);
        doc.text(`Cost: $${activity.cost}`, margin + 5, y);
        y += 5;
      }

      y += 3;
    });

    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(100, 100, 100);
    doc.text(`Day Total: $${day.totalCost}`, margin + 5, y);
    y += 10;
  });

  // Footer on last page
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by AI Vacation Planner", pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: "center" });

  // Save the PDF
  const filename = `${tripPlan.destination.name.replace(/\s+/g, "_")}_Itinerary.pdf`;
  doc.save(filename);
}
